### ISSUE TITLE
Container does not bootstrap configurations

### ISSUE THREAD

**Issue by JesseBowling** [ventz/docker-cif#5]
Hi all,

Upon bringing up a container using docker-compose, there are no configurations available to the CIF instance (i.e., ./etc/cif is missing cif-router.yml and csirtg-smrt.yml) nor is there an empty database. 

Unless you have something before then, or if this is actually an error, I'll try to come up with some code to bootstrap configs if there are none available at start time.

docker-compose.yml:
```
version: '2'
services:
  cif:
    image: ventz/cif:latest
    volumes:
      - ./etc/cif:/etc/cif
      - ./var/lib/cif:/var/lib/cif
      - ./var/log/cif:/var/log/cif
    ports:
      - "443:443"
      - "5000:5000"
```
